name: asn1lib
version: 0.8.1
description: An ASN1 parser library for Dart. Encodes / decodes from ASN1 Objects to BER bytes
homepage: https://github.com/wstrange/asn1lib
environment:
 sdk: '>=2.2.0 <3.0.0'
dev_dependencies:
  test: '>= 1.5.3'
  convert: '^2.0.1'
  pedantic: ^1.9.0
